[tool.flet]
project = "hOCG_H"
product = "hOCG_H"
org = "com.smalltyrant"
bundle_id = "com.smalltyrant.hocghelper"

[tool.flet.ios]
# iOS release testing build (for AltStore re-signing)
export_method = "release-testing"
info_plist = [
  "CFBundleDisplayName=hOCG_H",
  "CFBundleName=hOCG_H",
]

[tool.flet.splash]
ios = false
